from __future__ import annotations

import argparse
import json
import os
import zipfile
from pathlib import Path
from typing import Iterable


TEXT_EXTENSIONS = {
    ".py", ".toml", ".txt", ".md", ".yaml", ".yml", ".json", ".ini", ".cfg",
}

SKIP_DIRECTORY_NAMES = {
    ".git",
    ".idea",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "data",
    "models",
    "node_modules",
}

RELEVANT_ROLE_NAMES = {
    "fastapi_app",
    "router",
    "schema",
    "model_service",
    "image_validation",
    "exception_handler",
    "api_test",
    "streamlit_page",
    "api_client",
    "session_state",
    "opencv",
    "detection",
    "classification",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Export the repository files needed to implement Day 13 safely. "
            "Dataset files and model checkpoint binaries are excluded."
        )
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Repository root. Default: current working directory.",
    )
    parser.add_argument(
        "--inspection-artifact",
        type=Path,
        default=Path("reports/artifacts/day13_integration_prerequisites.json"),
        help="Inspection JSON generated by inspect_day13_integration_prerequisites.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("reports/artifacts/day13_repository_context.zip"),
        help="Output ZIP path relative to project root.",
    )
    return parser.parse_args()


def resolve(project_root: Path, path: Path) -> Path:
    return (path if path.is_absolute() else project_root / path).resolve()


def safe_relative(path: Path, root: Path) -> Path:
    return path.resolve().relative_to(root.resolve())


def is_safe_text_file(path: Path, project_root: Path) -> bool:
    try:
        relative = safe_relative(path, project_root)
    except ValueError:
        return False

    if path.suffix.lower() not in TEXT_EXTENSIONS:
        return False

    if any(part in SKIP_DIRECTORY_NAMES for part in relative.parts):
        return False

    if any(part.endswith("_candidate") for part in relative.parts):
        return False

    return path.is_file()


def files_from_report(report: dict, project_root: Path) -> Iterable[Path]:
    selected_paths: set[str] = set()

    files_by_role = report.get("summary", {}).get("files_by_role", {})
    for role, paths in files_by_role.items():
        if role in RELEVANT_ROLE_NAMES:
            selected_paths.update(str(path) for path in paths)

    mandatory_paths = {
        "README.md",
        "requirements.txt",
        "requirements-dev.txt",
        "pyproject.toml",
        "setup.cfg",
        "pytest.ini",
        "reports/artifacts/day13_integration_prerequisites.json",
    }
    selected_paths.update(mandatory_paths)

    for relative_text in sorted(selected_paths):
        candidate = (project_root / relative_text).resolve()
        if is_safe_text_file(candidate, project_root):
            yield candidate


def add_tree_files(project_root: Path, selected: set[Path]) -> None:
    for root_name in ("src", "tests", "scripts", "dashboard", "streamlit", "app"):
        root = project_root / root_name
        if not root.is_dir():
            continue

        for current_root, dirnames, filenames in os.walk(root):
            dirnames[:] = [
                name
                for name in dirnames
                if name not in SKIP_DIRECTORY_NAMES and not name.endswith("_candidate")
            ]
            for filename in filenames:
                path = Path(current_root) / filename
                if is_safe_text_file(path, project_root):
                    selected.add(path.resolve())


def main() -> int:
    args = parse_args()
    project_root = args.project_root.resolve()
    inspection_path = resolve(project_root, args.inspection_artifact)
    output_path = resolve(project_root, args.output)

    if not project_root.is_dir():
        print(f"[FAIL] Project root not found: {project_root}")
        return 2

    if not inspection_path.is_file():
        print(
            "[FAIL] Inspection artifact not found. Run "
            "scripts.inspect_day13_integration_prerequisites first."
        )
        return 3

    report = json.loads(inspection_path.read_text(encoding="utf-8"))
    selected: set[Path] = set(files_from_report(report, project_root))

    # 전체 텍스트 소스도 포함하여 누락된 호출 관계를 안전하게 확인할 수 있게 한다.
    add_tree_files(project_root, selected)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(
        output_path,
        mode="w",
        compression=zipfile.ZIP_DEFLATED,
        compresslevel=9,
    ) as archive:
        for path in sorted(selected):
            archive.write(
                filename=path,
                arcname=safe_relative(path, project_root).as_posix(),
            )

    print("=" * 100)
    print("DAY 13 - REPOSITORY CONTEXT EXPORT")
    print("=" * 100)
    print(f"Project root             : {project_root}")
    print(f"Exported text files      : {len(selected)}")
    print(f"Checkpoint binaries      : EXCLUDED")
    print(f"Dataset files            : EXCLUDED")
    print(f"Output                    : {output_path}")
    print("=" * 100)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
